services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: applyticz-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:Applyticz12@applyticzdb.cjsqs004ifhp.us-east-2.rds.amazonaws.com:3311/applytics_db
    volumes:
      - ./Backend:/app  # Mount the Backend folder for live reloading
      - /app/__pycache__  # Optional: Avoid caching issues by mounting the pycache folder
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8.0
    container_name: applyticz-db
    environment:
      MYSQL_ROOT_PASSWORD: Applyticz12
      MYSQL_DATABASE: applytics_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Applyticz12
    ports:
      - "3311:3311"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .  # Frontend build context
      dockerfile: Frontend/Dockerfile  # Path to the frontend Dockerfile
    container_name: applyticz-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/app:/app  # Bind mount for live reloading
    command: npm start
    depends_on:
      - backend

volumes:
  db_data:
