"""Add new columns to resumes and apps

Revision ID: 4fb3a5439810
Revises: a17e4b0e83ba
Create Date: 2024-09-20 09:56:54.732785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb3a5439810'
down_revision: Union[str, None] = 'a17e4b0e83ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('last_update', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('salary', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('job_description', sa.String(length=1000), nullable=True))
    op.add_column('resumes', sa.Column('modified_date', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('pdf_file', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'pdf_file')
    op.drop_column('resumes', 'modified_date')
    op.drop_column('applications', 'job_description')
    op.drop_column('applications', 'salary')
    op.drop_column('applications', 'last_update')
    op.drop_column('applications', 'location')
    # ### end Alembic commands ###
