"""Renaming pdf_file to pdf_data

Revision ID: 7db42c47b697
Revises: 941b47ccf93a
Create Date: 2024-09-28 20:23:07.309366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7db42c47b697'
down_revision: Union[str, None] = '941b47ccf93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('pdf_data', sa.LargeBinary(), nullable=False))
    op.drop_column('resumes', 'pdf_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('pdf_url', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('resumes', 'pdf_data')
    # ### end Alembic commands ###
