"""Updating Resumes to contain file data

Revision ID: 941b47ccf93a
Revises: 8acdd7aad207
Create Date: 2024-09-28 19:01:26.141583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941b47ccf93a'
down_revision: Union[str, None] = '8acdd7aad207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'pdf_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('pdf_file', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###
