"""Adding gmail auth table and updating applications table

Revision ID: ab4a36242e1a
Revises: d1c3d2a528c8
Create Date: 2024-11-19 15:47:55.314343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab4a36242e1a'
down_revision: Union[str, None] = 'd1c3d2a528c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('previous_emails', sa.String(length=1000), nullable=True))
    op.add_column('applications', sa.Column('days_to_update', sa.Integer(), nullable=True))
    op.alter_column('applications', 'applied_date',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('applications', 'last_update',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('applications', 'interview_dates',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('gmail_auth', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_auth', sa.Column('scope', mysql.VARCHAR(length=512), nullable=True))
    op.alter_column('applications', 'interview_dates',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('applications', 'last_update',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('applications', 'applied_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('applications', 'days_to_update')
    op.drop_column('applications', 'previous_emails')
    # ### end Alembic commands ###
