"""Test changes for Test model

Revision ID: c70fd0b21e8c
Revises: 7cbecb6602e4
Create Date: 2024-09-14 14:41:03.280853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70fd0b21e8c'
down_revision: Union[str, None] = '7cbecb6602e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'age')
    # ### end Alembic commands ###
