"""Alterered previous_emails column

Revision ID: cd29f2081d05
Revises: ab4a36242e1a
Create Date: 2024-11-19 16:20:31.423873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd29f2081d05'
down_revision: Union[str, None] = 'ab4a36242e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'previous_emails',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'previous_emails',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
