"""Update settings table to account for refresh time

Revision ID: faba6631f3df
Revises: 0424ce276508
Create Date: 2024-11-20 16:05:43.420565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faba6631f3df'
down_revision: Union[str, None] = '0424ce276508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('last_refresh_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'last_refresh_time')
    # ### end Alembic commands ###
